### ISSUE TITLE
NVD data feed의 XML을 더이상 지원하지 않는 것으로 보입니다.

### ISSUE THREAD

**Issue by kimbyungnam** [squizz617/vulnDBGen#2]
initialize.py를 구동할 때 nvd 사이트에서 연도별 nvcdcve xml.zip 파일을 다운로드 받게 되는데 현재 nvd에서 XML 형식의 지원을 중단한 것으로 보입니다. 이로 인해 툴을 사용하는데 어려움을 겪고 있는데 좋은 해결책이 있을까요?

**Comment by squizz617** [comment]
NVD의 JSON Feed를 사용하도록 패치했습니다 (commit 0ae9367). 신규 버젼을 이용해 주시기 바랍니다.

**Comment by kimbyungnam** [comment]
tools/cvedatagen/cveXmlDownloader.py 의 14번째 라인의 return을 제거해야 정상작동하는 것으로 보입니다. 현재 버전(commit 0ae9367)을 그대로 사용했을 때 CVEXML 디렉토리가 없다는 에러가 발생합니다. return 제거 후 정상 작동되는 것을 확인했습니다.

**Comment by squizz617** [comment]
디버깅 코드를 커밋해버렸네요. 덕분에 수정했습니다. 감사합니다. 이슈는 close하겠습니다 :)
